import type { BrowserState } from './types';

export const initialState: BrowserState = {
  version: 1,
  activeWorkspaceId: 'ws-linkedin',
  workspaces: [
    {
      id: 'ws-linkedin',
      name: 'Founder Voice',
      profileId: 'ua-mac',
      platform: 'linkedin',
      accountHandle: '@alex.morgan',
      status: 'ready',
      accent: '#7c5cff',
      lastActive: 'Now',
    },
    {
      id: 'ws-x',
      name: 'Product Updates',
      profileId: 'ua-windows',
      platform: 'x',
      accountHandle: '@northstarhq',
      status: 'ready',
      accent: '#40d9a0',
      lastActive: '12m',
    },
    {
      id: 'ws-instagram',
      name: 'Studio Visuals',
      profileId: 'ua-iphone',
      platform: 'instagram',
      accountHandle: '@northstar.studio',
      status: 'attention',
      accent: '#ff8d69',
      lastActive: '2h',
    },
  ],
  uaProfiles: [
    {
      id: 'ua-mac',
      name: 'Chrome · macOS',
      platform: 'macOS 15',
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36',
      viewport: '1440 × 900',
      locale: 'en-US',
      timezone: 'America/New_York',
      clientHints: true,
      color: '#7c5cff',
    },
    {
      id: 'ua-windows',
      name: 'Chrome · Windows',
      platform: 'Windows 11',
      userAgent:
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36',
      viewport: '1536 × 864',
      locale: 'en-US',
      timezone: 'America/New_York',
      clientHints: true,
      color: '#40d9a0',
    },
    {
      id: 'ua-iphone',
      name: 'Safari · iPhone 16',
      platform: 'iOS 18',
      userAgent:
        'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',
      viewport: '393 × 852',
      locale: 'en-US',
      timezone: 'America/Los_Angeles',
      clientHints: false,
      color: '#ff8d69',
    },
    {
      id: 'ua-android',
      name: 'Chrome · Pixel 9',
      platform: 'Android 15',
      userAgent:
        'Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro) AppleWebKit/537.36 Chrome/131.0.0.0 Mobile Safari/537.36',
      viewport: '412 × 915',
      locale: 'en-US',
      timezone: 'America/Chicago',
      clientHints: true,
      color: '#4bb3fd',
    },
  ],
  drafts: [
    {
      id: 'draft-1',
      workspaceId: 'ws-linkedin',
      platform: 'linkedin',
      body: 'Most teams do not have an AI problem. They have a context problem. The work gets better when the model can see the decisions that shaped it.',
      status: 'scheduled',
      scheduledFor: new Date(Date.now() + 86400000).toISOString(),
      approvedBy: 'Alex Morgan',
      approvedAt: new Date(Date.now() - 3600000).toISOString(),
      postUrl: null,
      lastError: null,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'draft-2',
      workspaceId: 'ws-x',
      platform: 'x',
      body: 'Shipping the smallest useful version is a strategy, not a compromise.',
      status: 'draft',
      scheduledFor: null,
      approvedBy: null,
      approvedAt: null,
      postUrl: null,
      lastError: null,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'draft-3',
      workspaceId: 'ws-instagram',
      platform: 'instagram',
      body: 'A look behind the build: fewer meetings, sharper decisions, better work.',
      status: 'scheduled',
      scheduledFor: new Date(Date.now() + 172800000).toISOString(),
      approvedBy: 'Alex Morgan',
      approvedAt: new Date(Date.now() - 7200000).toISOString(),
      postUrl: null,
      lastError: null,
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      updatedAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  accounts: [
    {
      id: 'account-1',
      workspaceId: 'ws-linkedin',
      platform: 'linkedin',
      handle: '@alex.morgan',
      displayName: 'Alex Morgan',
      connected: true,
      avatar: 'AM',
    },
    {
      id: 'account-2',
      workspaceId: 'ws-x',
      platform: 'x',
      handle: '@northstarhq',
      displayName: 'Northstar',
      connected: true,
      avatar: 'NS',
    },
    {
      id: 'account-3',
      workspaceId: 'ws-instagram',
      platform: 'instagram',
      handle: '@northstar.studio',
      displayName: 'Northstar Studio',
      connected: false,
      avatar: 'ST',
    },
  ],
  activity: [
    {
      id: 'activity-1',
      title: 'AI variants generated',
      detail: '3 LinkedIn options for Founder Voice',
      timestamp: '4 min ago',
      type: 'ai',
    },
    {
      id: 'activity-2',
      title: 'Draft scheduled',
      detail: 'Studio Visuals · tomorrow at 10:30',
      timestamp: '28 min ago',
      type: 'draft',
    },
    {
      id: 'activity-3',
      title: 'Workspace isolated',
      detail: 'Product Updates opened with Chrome · Windows',
      timestamp: '1 hr ago',
      type: 'workspace',
    },
  ],
  settings: {
    theme: 'dark',
    operatorName: 'Alex Morgan',
    confirmBeforePublish: true,
    storeAiPrompts: false,
    model: 'GLM-4-32B',
    provider: 'pin',
  },
  usage: { inputTokens: 14820, outputTokens: 6240, requests: 48 },
  updatedAt: new Date().toISOString(),
};